require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

platform :ios, '11.0'

target 'CourierTracker' do
  pod 'RNFS', :path => '../node_modules/react-native-fs'
  use_unimodules!
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
  

  target 'CourierTrackerTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({ 'Flipper' => '0.74.0' })
  post_install do |installer|
    flipper_post_install(installer)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
          config.build_settings['OTHER_CPLUSPLUSFLAGS'] = '-DDONT_AUTOINSTALL_REANIMATED'
      end
  end
  end
end

target 'CourierTracker-tvOS' do
  # Pods for CourierTracker-tvOS

  target 'CourierTracker-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
